version: '3'

services:
  web-api:
    build: 
      context: ./WebAPI
      dockerfile: ./WebAPI/Dockerfile
    ports:
      - "5000:80"
  frontend:
    build: 
      context: ./reactapp
      dockerfile: ./Dockerfile
    volumes:
        - "./reactapp:/bindmount:rw"
    ports:
        - "3000:3000"